QUBO/Models/Pager.cs
namespace QUBO.Models
{
    public class Pager
    {
        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }

        public Pager() { }
        public Pager(int totalitems, int page, int pagesize = 10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalitems / (decimal)pagesize);
            int currentPage = page;

            int startpage = currentPage - 5;
            int endpage = currentPage + 4;

            if (startpage <= 0)
            {
                endpage = endpage - (startpage - 1);
                startpage = 1;
            }
            if (endpage > totalPages)
            {
                endpage = totalPages;
                if (endpage > 10)
                {
                    startpage = endpage - 9;
                }
            }

            TotalItems = totalitems;
            CurrentPage = currentPage;
            PageSize = pagesize;
            TotalPages = totalPages;
            StartPage = startpage;
            EndPage = endpage;
        }
    }
}

QUBO/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly QuboDbContext _context;
        private readonly IPasswordHasher<Usuario> _passwordHasher;
        public UsuariosController(QuboDbContext context, IPasswordHasher<Usuario> passwordHasher)
        {
            _context = context;
            _passwordHasher = passwordHasher;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,Contrasenia,RolUsuario,Apellido,Dni,Telefono")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                // Verificar si ya existe un usuario con el mismo DNI
                var existingUserByDni = await _context.Usuarios
                    .FirstOrDefaultAsync(u => u.Dni == usuario.Dni);

                if (existingUserByDni != null)
                {
                    ViewData["Mensaje"] = "Error: Ya existe un usuario con el mismo DNI.";
                    return View();
                }

                // Verificar si ya existe un usuario con la misma contraseña
                var allUsers = await _context.Usuarios.ToListAsync();
                foreach (var user in allUsers)
                {
                    var verificationResult = _passwordHasher.VerifyHashedPassword(user, user.Contrasenia!, usuario.Contrasenia!);
                    if (verificationResult == PasswordVerificationResult.Success)
                    {
                        ViewData["Mensaje"] = "Error: Ya existe un usuario con la misma contraseña.";
                        return View();
                    }
                }

                // Hashear la contraseña y guardar el usuario
                usuario.Contrasenia = _passwordHasher.HashPassword(usuario, usuario.Contrasenia!);
                _context.Add(usuario);
                await _context.SaveChangesAsync();

                // Verificar si el usuario fue creado exitosamente
                if (usuario.IdUsuario != 0)
                {
                    ViewData["Mensaje"] = "Usuario creado exitosamente.";
                }
                else
                {
                    ViewData["Mensaje"] = "Error: No se pudo crear el usuario.";
                }
                return View();
            }
            return View();
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdUsuario,Nombre,Contrasenia,RolUsuario,Apellido,Dni,Telefono")] Usuario usuario)
        {
            if (id != usuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(long id)
        {
            return _context.Usuarios.Any(e => e.IdUsuario == id);
        }
    }
}

QUBO/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QUBO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QUBO.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QUBO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* Obtener el rol del usuario de la sesión *@
                @{
                    var rolUsuario = HttpContextAccessor.HttpContext!.Session.GetString("RolUsuario");
                }
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-red" asp-area="" asp-controller="Arreglo" asp-action="Index">Historial</a>
                        </li>
                        @if (rolUsuario == "ADMINISTRADOR")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-red" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <form asp-area="" asp-controller="Acceso" asp-action="Logout" method="post" class="form-inline">
                                <button type="submit" class="btn btn-danger btn-link nav-link text-light">Cerrar sesión</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QUBO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QUBO/Views/Shared/_Pager.cshtml
@model QUBO.Models.Pager
@{
}

<div class="container">
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Arreglo" asp-action="Index" asp-route-pg="1">
                        Primero
                    </a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Arreglo" asp-action="Index" asp-route-pg="@Model.CurrentPage - 1">
                        Anterior
                    </a>
                </li>
            }

            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Arreglo" asp-action="Index" asp-route-pg="@pge"> @pge </a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Arreglo" asp-action="Index" asp-route-pg="@Model.CurrentPage + 1">
                        Siguiente
                    </a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Arreglo" asp-action="Index" asp-route-pg="@Model.TotalPages">
                        Ultimo
                    </a>
                </li>
            }
        </ul>
    }
</div>