QUBO/Models/DetalleArreglo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace QUBO.Models;

public partial class DetalleArreglo
{
    public long IdDetalle { get; set; }

    public long? IdArreglo { get; set; }

    public long? IdParte { get; set; }

    [Display(Name = "Descripción")]
    public string? Descripcion { get; set; }

    public virtual Arreglo? IdArregloNavigation { get; set; }

    public virtual Parte? IdParteNavigation { get; set; }
}

QUBO/Controllers/DetalleArregloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class DetalleArregloController : Controller
    {
        private readonly QuboDbContext _context;

        public DetalleArregloController(QuboDbContext context)
        {
            _context = context;
        }
        /*
        // GET: DetalleArreglo
        public async Task<IActionResult> Index()
        {
            var quboDbContext = _context.DetalleArreglos.Include(d => d.IdArregloNavigation).Include(d => d.IdParteNavigation);
            return View(await quboDbContext.ToListAsync());
        }
        */
        // GET: DetalleArreglo
        public async Task<IActionResult> Index(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quboDbContext = _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .Where(d => d.IdArregloNavigation!.IdArreglo == id); // Accede a la clave primaria de Arreglo

            ViewBag.IdArreglo = id;
            return View(await quboDbContext.ToListAsync());
        }
        // GET: DetalleArreglo/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalle == id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }

            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Create
        public async Task<IActionResult> Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Obtener el arreglo correspondiente al id proporcionado
            var arreglo = await _context.Arreglos
                .FirstOrDefaultAsync(a => a.IdArreglo == id);
            if (arreglo == null)
            {
                return NotFound();
            }

            ViewBag.IdCelular = arreglo.IdCelular;
            ViewBag.IdArreglo = id;
            ViewData["IdParte"] = new SelectList(_context.Partes.Where(p=> p.IdCelular == arreglo.IdCelular), "IdPartes", "Nombre");
            return View();
        }

        // POST: DetalleArreglo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDetalle,IdArreglo,IdParte,Descripcion")] DetalleArreglo detalleArreglo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detalleArreglo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = detalleArreglo.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
            }
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes, "IdPartes", "Nombre", detalleArreglo.IdParte);
            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos.FindAsync(id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }
            var arreglo = await _context.Arreglos
                .FirstOrDefaultAsync(a => a.IdArreglo == detalleArreglo.IdArreglo);
            
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes.Where(p => p.IdCelular == arreglo!.IdCelular), "IdPartes", "Nombre", detalleArreglo.IdParte); //CAMBIAR
            return View(detalleArreglo);
        }

        // POST: DetalleArreglo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdDetalle,IdArreglo,IdParte,Descripcion")] DetalleArreglo detalleArreglo)
        {
            if (id != detalleArreglo.IdDetalle)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalleArreglo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleArregloExists(detalleArreglo.IdDetalle))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = detalleArreglo.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
            }
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes, "IdPartes", "Nombre", detalleArreglo.IdParte);
            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalle == id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }

            return View(detalleArreglo);
        }

        // POST: DetalleArreglo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var detalleArreglo = await _context.DetalleArreglos.FindAsync(id);
            if (detalleArreglo != null)
            {
                _context.DetalleArreglos.Remove(detalleArreglo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = detalleArreglo?.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
        }

        private bool DetalleArregloExists(long id)
        {
            return _context.DetalleArreglos.Any(e => e.IdDetalle == id);
        }
    }
}

QUBO/Controllers/ParteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class ParteController : Controller
    {
        private readonly QuboDbContext _context;

        public ParteController(QuboDbContext context)
        {
            _context = context;
        }

        // GET: Parte
        public async Task<IActionResult> Index(long? id)
        {
            var quboDbContext = _context.Partes.Include(p => p.IdCelularNavigation)
                                .Where(p => p.IdCelularNavigation!.IdCelular == id);
            if (id == null)
            {
                quboDbContext = _context.Partes.Include(p => p.IdCelularNavigation);
            }
             
            return View(await quboDbContext.ToListAsync());
        }

        // GET: Parte/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.Partes
                .Include(p => p.IdCelularNavigation)
                .FirstOrDefaultAsync(m => m.IdPartes == id);
            if (parte == null)
            {
                return NotFound();
            }

            return View(parte);
        }
        public IActionResult Create(long? id)
        {
            ViewBag.IdExists = false;
            if (id != null )
            {
                ViewBag.IdExists = true;
                ViewBag.IdCelular = id;
            }
            else
            {
                ViewData["IdCelular"] = new SelectList(_context.Celulars, "IdCelular", "Modelo");
            }
            return View();
        }

        // POST: Parte/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(long? id,[Bind("IdPartes,Nombre,Modelo,PrecioUsd,CodigoProducto,IdCelular")] Parte parte)
        {
            if (ModelState.IsValid)
            {
                _context.Add(parte);
                await _context.SaveChangesAsync();
                if (id != null)
                {
                    return RedirectToAction("Create","DetalleArreglo", new { id });
                }
                else { 
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["IdCelular"] = new SelectList(_context.Celulars, "IdCelular", "Modelo", parte.IdCelular);
            return View(parte);
        }

        // GET: Parte/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.Partes.FindAsync(id);
            if (parte == null)
            {
                return NotFound();
            }
            ViewData["IdCelular"] = new SelectList(_context.Celulars, "IdCelular", "Modelo", parte.IdCelular);
            return View(parte);
        }

        // POST: Parte/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdPartes,Nombre,Modelo,PrecioUsd,CodigoProducto,IdCelular")] Parte parte)
        {
            if (id != parte.IdPartes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parte);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParteExists(parte.IdPartes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCelular"] = new SelectList(_context.Celulars, "IdCelular", "Modelo", parte.IdCelular);
            return View(parte);
        }

        // GET: Parte/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.Partes
                .Include(p => p.IdCelularNavigation)
                .FirstOrDefaultAsync(m => m.IdPartes == id);
            if (parte == null)
            {
                return NotFound();
            }

            return View(parte);
        }

        // POST: Parte/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var parte = await _context.Partes.FindAsync(id);
            if (parte != null)
            {
                _context.Partes.Remove(parte);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParteExists(long id)
        {
            return _context.Partes.Any(e => e.IdPartes == id);
        }
    }
}

QUBO/Views/DetalleArreglo/Create.cshtml
@model QUBO.Models.DetalleArreglo
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Create";
    var rolUsuario = HttpContextAccessor.HttpContext!.Session.GetString("RolUsuario");
}

<h1>Crear</h1>

<h4>Detalle del Arreglo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdArreglo" value="@ViewBag.IdArreglo" />
            <div class="form-group">
                <label asp-for="IdParte" class="control-label"></label>
                <select asp-for="IdParte" class ="form-control" asp-items="ViewBag.IdParte"></select>
            </div>
            @if (rolUsuario == "ADMINISTRADOR")
            {
                <div>
                    <a asp-controller="Parte" asp-action="Create" asp-route-id="@ViewBag.IdCelular" class="btn btn-info">Nueva Parte</a>
                </div>
            }
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger" asp-route-id="@ViewBag.IdArreglo">Cancelar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QUBO/Views/DetalleArreglo/Delete.cshtml
@model QUBO.Models.DetalleArreglo

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Registro a eliminar:</h3>
<div>
    <h4>DetalleArreglo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdArregloNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdArregloNavigation!.IdArreglo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdParteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdParteNavigation!.IdPartes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDetalle" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info" asp-route-id="@Model?.IdArreglo">Volver</a>
    </form>
</div>

QUBO/Views/DetalleArreglo/Details.cshtml
@model QUBO.Models.DetalleArreglo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Parte:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdParteNavigation!.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        @*
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdArregloNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdArregloNavigation!.IdArreglo)
        </dd>
        *@
    </dl>
</div>
<div>
    <a asp-action="Editar" class="btn btn-success" asp-route-id="@Model?.IdDetalle">Editar</a> |
    <a asp-action="Index" class="btn btn-info" asp-route-id="@Model?.IdArreglo">Volver</a>
</div>

QUBO/Views/DetalleArreglo/Edit.cshtml
@model QUBO.Models.DetalleArreglo

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Detalle del Arreglo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDetalle" />
            <input type="hidden" asp-for="IdArreglo" />
            <div class="form-group">
                <label asp-for="IdParte" class="control-label"></label>
                <select asp-for="IdParte" class="form-control" asp-items="ViewBag.IdParte"></select>
                <span asp-validation-for="IdParte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger" asp-route-id="@Model?.IdArreglo">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QUBO/Views/DetalleArreglo/Index.cshtml
@model IEnumerable<QUBO.Models.DetalleArreglo>
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
    var rolUsuario = HttpContextAccessor.HttpContext!.Session.GetString("RolUsuario");
}

<h1>Index</h1>
@if (rolUsuario == "ADMINISTRADOR" || rolUsuario == "VENDEDOR")
{
    <p>
    <a asp-action="Create" class="btn btn-success" asp-route-id="@ViewBag.IdArreglo">Agregar Nuevo <i class="bi bi-plus-lg"></i></a>
    </p>
}
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th class="text-center">
                Parte
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdParteNavigation!.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
                <td class="text-center">
                    <a asp-action="Edit" asp-route-id="@item.IdDetalle" class="btn btn-success" data-bs-toggle="tooltip" title="Editar">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    <a asp-action="Details" asp-route-id="@item.IdDetalle" class="btn btn-primary" data-bs-toggle="tooltip" title="Detalles">
                        <i class="bi bi-info-square"></i>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.IdDetalle" class="btn btn-danger" data-bs-toggle="tooltip" title="Eliminar">
                        <i class="bi bi-x-square"></i>
                    </a>
                </td>
        </tr>
}
    </tbody>
</table>