QUBO/Controllers/CelularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class CelularController : Controller
    {
        private readonly QuboDbContext _context;

        public CelularController(QuboDbContext context)
        {
            _context = context;
        }
        //Get Celular por producto
        [HttpGet]
        public async Task<JsonResult> GetCelularesByCod(string term)
        {
            var celulares = await _context.Celulars
                .Where(c => c.CodigoProducto!.Contains(term))
                .Select(c => new { c.IdCelular, c.CodigoProducto })
                .ToListAsync();

            return Json(celulares);
        }

        //Partial
        public IActionResult CreatePartial()
        {
            return PartialView("_CelularPartial", new Celular());
        }
        // GET: Celular
        public async Task<IActionResult> Index()
        {
            return View(await _context.Celulars.ToListAsync());
        }

        // GET: Celular/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var celular = await _context.Celulars
                .FirstOrDefaultAsync(m => m.IdCelular == id);
            if (celular == null)
            {
                return NotFound();
            }

            return View(celular);
        }

        // GET: Celular/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Celular/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCelular,Modelo,Marca,CodigoProducto,PrecioUsd")] Celular celular)
        {
            if (ModelState.IsValid)
            {
                _context.Add(celular);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(celular);
        }

        // GET: Celular/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var celular = await _context.Celulars.FindAsync(id);
            if (celular == null)
            {
                return NotFound();
            }
            return View(celular);
        }

        // POST: Celular/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdCelular,Modelo,Marca,CodigoProducto,PrecioUsd")] Celular celular)
        {
            if (id != celular.IdCelular)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(celular);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CelularExists(celular.IdCelular))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(celular);
        }

        // GET: Celular/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var celular = await _context.Celulars
                .FirstOrDefaultAsync(m => m.IdCelular == id);
            if (celular == null)
            {
                return NotFound();
            }

            return View(celular);
        }

        // POST: Celular/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var celular = await _context.Celulars.FindAsync(id);
            if (celular != null)
            {
                _context.Celulars.Remove(celular);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CelularExists(long id)
        {
            return _context.Celulars.Any(e => e.IdCelular == id);
        }
    }
}

QUBO/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly QuboDbContext _context;


        public ClienteController(QuboDbContext context)
        {
            _context = context;
        }
        
        //Get Clientes por Dni
        [HttpGet]
        public async Task<JsonResult> GetClientesByDni(string term)
        {
            var clientes = await _context.Clientes
                .Where(c => c.Dni!.Contains(term))
                .Select(c => new { c.IdCliente, c.Dni })
                .ToListAsync();

            return Json(clientes);
        }

        //Partial
        public IActionResult CreatePartial()
        {
            return PartialView("_ClientePartial", new Cliente());
        }
        // GET: Cliente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Cliente/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,Nombre,Dni,Telefono,Email")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }
        
        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdCliente,Nombre,Dni,Telefono,Email")] Cliente cliente)
        {
            if (id != cliente.IdCliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.IdCliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(long id)
        {
            return _context.Clientes.Any(e => e.IdCliente == id);
        }
    }
}

QUBO/Controllers/DetalleArregloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QUBO.Models;
using Microsoft.AspNetCore.Authorization;

namespace QUBO.Controllers
{
    [Authorize]
    public class DetalleArregloController : Controller
    {
        private readonly QuboDbContext _context;

        public DetalleArregloController(QuboDbContext context)
        {
            _context = context;
        }
        /*
        // GET: DetalleArreglo
        public async Task<IActionResult> Index()
        {
            var quboDbContext = _context.DetalleArreglos.Include(d => d.IdArregloNavigation).Include(d => d.IdParteNavigation);
            return View(await quboDbContext.ToListAsync());
        }
        */
        // GET: DetalleArreglo
        public async Task<IActionResult> Index(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quboDbContext = _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .Where(d => d.IdArregloNavigation!.IdArreglo == id); // Accede a la clave primaria de Arreglo

            ViewBag.IdArreglo = id;
            return View(await quboDbContext.ToListAsync());
        }
        // GET: DetalleArreglo/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalle == id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }

            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Create
        public async Task<IActionResult> Create(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Obtener el arreglo correspondiente al id proporcionado
            var arreglo = await _context.Arreglos
                .FirstOrDefaultAsync(a => a.IdArreglo == id);
            if (arreglo == null)
            {
                return NotFound();
            }

            ViewBag.IdCelular = arreglo.IdCelular;
            ViewBag.IdArreglo = id;
            ViewData["IdParte"] = new SelectList(_context.Partes.Where(p=> p.IdCelular == arreglo.IdCelular), "IdPartes", "Nombre");
            return View();
        }

        // POST: DetalleArreglo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDetalle,IdArreglo,IdParte,Descripcion")] DetalleArreglo detalleArreglo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detalleArreglo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = detalleArreglo.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
            }
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes, "IdPartes", "Nombre", detalleArreglo.IdParte);
            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos.FindAsync(id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }
            var arreglo = await _context.Arreglos
                .FirstOrDefaultAsync(a => a.IdArreglo == detalleArreglo.IdArreglo);
            
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes.Where(p => p.IdCelular == arreglo!.IdCelular), "IdPartes", "Nombre", detalleArreglo.IdParte); //CAMBIAR
            return View(detalleArreglo);
        }

        // POST: DetalleArreglo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdDetalle,IdArreglo,IdParte,Descripcion")] DetalleArreglo detalleArreglo)
        {
            if (id != detalleArreglo.IdDetalle)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalleArreglo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleArregloExists(detalleArreglo.IdDetalle))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = detalleArreglo.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
            }
            ViewData["IdArreglo"] = new SelectList(_context.Arreglos, "IdArreglo", "IdArreglo", detalleArreglo.IdArreglo);
            ViewData["IdParte"] = new SelectList(_context.Partes, "IdPartes", "Nombre", detalleArreglo.IdParte);
            return View(detalleArreglo);
        }

        // GET: DetalleArreglo/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleArreglo = await _context.DetalleArreglos
                .Include(d => d.IdArregloNavigation)
                .Include(d => d.IdParteNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalle == id);
            if (detalleArreglo == null)
            {
                return NotFound();
            }

            return View(detalleArreglo);
        }

        // POST: DetalleArreglo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var detalleArreglo = await _context.DetalleArreglos.FindAsync(id);
            if (detalleArreglo != null)
            {
                _context.DetalleArreglos.Remove(detalleArreglo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = detalleArreglo?.IdArreglo }); // Redirigir a la vista de detalles del idArreglo
        }

        private bool DetalleArregloExists(long id)
        {
            return _context.DetalleArreglos.Any(e => e.IdDetalle == id);
        }
    }
}

QUBO/Views/Arreglo/Create.cshtml
@model QUBO.Models.Arreglo

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Arreglo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label for="ClienteDni" class="control-label">Cliente DNI</label>
                <div class="input-group">
                    <input type="text" id="ClienteDni" class="form-control" />
                    <input type="hidden" id="IdCliente" name="IdCliente" />
                    <button type="button" class="btn btn-primary" style="display:none;" id="btnAgregarCliente" onclick="loadForm('@Url.Action("CreatePartial", "Cliente")', 'Crear Cliente')">
                        <i class="bi bi-plus-circle-fill"></i>
                    </button>
                </div>
                <small id="dniHelp" class="form-text text-muted" style="display:none;">Por favor, ingrese el DNI del cliente.</small>
            </div>
            <div class="form-group">
                <label for="CelularCodigo" class="control-label">Codigo de Celular</label>
                <div class="input-group">
                    <input type="text" id="CelularCodigo" class="form-control" />
                    <input type="hidden" id="IdCelular" name="IdCelular" />
                    <button type="button" class="btn btn-primary" style="display:none;" id="btnAgregarCelular" onclick="loadForm('@Url.Action("CreatePartial", "Celular")', 'Crear Celular')">
                        <i class="bi bi-plus-circle-fill"></i>
                    </button>
                </div>
                <small id="codigoHelp" class="form-text text-muted" style="display:none;">Por favor, ingrese el Codigo del cliente.</small>
            </div>
            <!--
            <div class="form-group">
                <label asp-for="IdCelular" class="control-label"></label>
                <select asp-for="IdCelular" class="form-control" asp-items="ViewBag.IdCelular"></select>
            </div>
            -->
            <div class="form-group">
                <label asp-for="Problema" class="control-label"></label>
                <input asp-for="Problema" class="form-control" />
                <span asp-validation-for="Problema" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIng" class="control-label"></label>
                <input asp-for="FechaIng" class="form-control" />
                <span asp-validation-for="FechaIng" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label">Total</label>
                <input asp-for="Total" class="form-control" type="number"/>
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senia" class="control-label">Seña</label>
                <input asp-for="Senia" class="form-control" type="number"/>
                <span asp-validation-for="Senia" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label">Tecnico</label>
                <select asp-for="IdUsuario" class="form-control" asp-items="ViewBag.IdUsuario"></select>
            </div>

            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="Entrante">Entrante</option>
                    <option value="Reparando">Reparando</option>
                    <option value="Terminado">Terminado</option>
                    <option value="Entregado">Entregado</option>
                    <option value="Sin reparacion">Sin reparacion</option>
                    <option value="Sin falla encontrada">Sin falla encontrada</option>
                    <option value="Esperando confirmacion">Esperando confirmacion</option>
                    <option value="Esperando repuesto">Esperando repuesto</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>

<!-- Modal genérico para formularios -->
<div class="modal fade" id="genericModal" tabindex="-1" aria-labelledby="genericModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="genericModalLabel">Formulario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="genericFormContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" id="submitGenericForm" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />

    <script>
    $(function () {
        // Función para cargar formularios en el modal genérico
        function loadForm(url, modalTitle) {
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    $('#genericFormContainer').html(data);
                    $('#genericModalLabel').text(modalTitle);
                    $('#genericModal').modal('show');
                },
                error: function (error) {
                    console.error('Error al cargar el formulario:', error);
                }
            });
        }

        // Mostrar modal con formulario de cliente
        $('#btnAgregarCliente').on('click', function () {
            loadForm('@Url.Action("CreatePartial", "Cliente")', 'Crear Cliente');
            $("#ClienteDni").val('');
        });
        
        // Mostrar modal con formulario de celular
        $('#btnAgregarCelular').on('click', function () {
            loadForm('@Url.Action("CreatePartial", "Celular")', 'Crear Celular');
            $("#ClienteCodigo").val('');
        });

        // Función para enviar el formulario genérico
        $('#submitGenericForm').on('click', function () {
            var form = $('#genericFormContainer').find('form');
            $.ajax({
                url: form.attr('action'),
                method: 'POST',
                data: form.serialize(),
                success: function (data) {
                    // Ocultar el modal después de guardar
                    $('#genericModal').modal('hide');
                    // Mostrar mensaje o realizar otras acciones si es necesario
                    alert('Formulario guardado con éxito');
                },
                error: function (error) {
                    console.error('Error al guardar el formulario:', error);
                }
            });
        });

        // Sugerencia genérica
        function setupAutocomplete(inputSelector, hiddenInputSelector, buttonSelector, helpTextSelector, ajaxUrl, mapFunction) {
            $(inputSelector).autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: ajaxUrl,
                        data: { term: request.term },
                        success: function (data) {
                            if (data.length === 0) {
                                $(buttonSelector).show();
                                $(helpTextSelector).show();
                            } else {
                                $(buttonSelector).hide();
                                $(helpTextSelector).hide();
                            }
                            response($.map(data, mapFunction));
                        }
                    });
                },
                select: function (event, ui) {
                    $(hiddenInputSelector).val(ui.item.id);
                    $(buttonSelector).hide();
                    $(helpTextSelector).hide();
                },
                change: function (event, ui) {
                    if (!ui.item) {
                        var currentInput = $(inputSelector).val();
                        $.ajax({
                            url: ajaxUrl,
                            data: { term: currentInput },
                            success: function (data) {
                                var match = data.find(item => item.dni === currentInput || item.codigoProducto === currentInput);
                                if (match) {
                                    $(hiddenInputSelector).val(match.idCliente || match.idCelular);
                                    $(buttonSelector).hide();
                                    $(helpTextSelector).hide();
                                } else {
                                    $(hiddenInputSelector).val('');
                                    $(buttonSelector).show();
                                    $(helpTextSelector).show();
                                }
                            }
                        });
                    }
                }
            });
        }

        // Configurar autocompletado genérico
        //CLIENTE
        setupAutocomplete(
            "#ClienteDni",
            "#IdCliente",
            "#btnAgregarCliente",
            "#dniHelp",
            '@Url.Action("GetClientesByDni", "Cliente")',
            function (item) {
                return {
                    label: item.dni,
                    value: item.dni,
                    id: item.idCliente
                };
            }
        );

        //CELULAR
        setupAutocomplete(
            "#CelularCodigo",
            "#IdCelular",
            "#btnAgregarCelular",
            "#codigoHelp",
            '@Url.Action("GetCelularesByCod", "Celular")',
            function (item) {
                return {
                    label: item.codigoProducto,
                    value: item.codigoProducto,
                    id: item.idCelular
                };
            }
        );

        // Limpiar input al hacer clic en agregar cliente
        $("#btnAgregarCliente").on('click', function () {
            $("#ClienteDni").val('');
        });
        $("#btnAgregarCelular").on('click', function () {
            $("#CelularCodigo").val('');
        });
    });
</script>
}

QUBO/Views/Arreglo/Details.cshtml
@model QUBO.Models.Arreglo
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Details";
    var rolUsuario = HttpContextAccessor.HttpContext!.Session.GetString("RolUsuario");
}

<h1>Detalles</h1>

<div>
    <h4>Arreglo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Problema)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Problema)
        </dd>
        <dt class = "col-sm-2">
            Fecha de Ingreso
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaIng)
        </dd>
        <dt class = "col-sm-2">
            Fecha de Entrega
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEnt)
        </dd>
        <dt class = "col-sm-2">
            Seña
        </dt>
        <dd class = "col-sm-10">
            @{
                var cultureInfoSenia = new System.Globalization.CultureInfo("es-AR");
                string seniaFormatted = String.Format(cultureInfoSenia, "{0:C}", Model.Senia);
            }
            @seniaFormatted
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @{
                var cultureInfoTotal = new System.Globalization.CultureInfo("es-AR");
                string totalFormatted = String.Format(cultureInfoTotal, "{0:C}", Model.Total);
            }

            @totalFormatted
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            Codigo de Producto
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCelularNavigation!.CodigoProducto)
        </dd>
        <dt class = "col-sm-2">
            Dni del Cliente
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation!.Dni)
        </dd>
        <dt class = "col-sm-2">
            Tecnico
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuarioNavigation!.Nombre)
            @Html.DisplayFor(model => model.IdUsuarioNavigation!.Apellido)
        </dd>
    </dl>
    <div>
        <a asp-controller="DetalleArreglo" asp-action="Index" asp-route-id="@Model.IdArreglo" class="btn btn-info">Ver Detalles del Arreglo</a>
    </div>
</div>
<hr />
<div>
    @if (rolUsuario == "ADMINISTRADOR" || rolUsuario == "VENDEDOR") 
    {<a asp-action="Edit" asp-route-id="@Model?.IdArreglo" class="btn btn-success">Editar</a>}

    <a asp-action="Index" class="btn btn-primary">Volver</a>
</div>